### ISSUE TITLE
add color to the script yd

### ISSUE THREAD

**Issue by whoisnian** [rocka/dotFiles#1]
Thank you for your script `yd`. It works well with my krunner. 
I think it will be more beautiful with color.
```
sed ':a;N;$!ba;s/\n/<br\/>/g;
        s/ /\&nbsp;/g;
        s/\o33\[1m/<font style="font-weight:bold;">/g;
        s/\o33\[4m/<font style="text-decoration:underline;">/g;
        s/\o33\[30m/<font style="color:black;">/g;
        s/\o33\[31m/<font style="color:red;">/g;
        s/\o33\[32m/<font style="color:green;">/g;
        s/\o33\[33m/<font style="color:darkorange;">/g;
        s/\o33\[34m/<font style="color:blue;">/g;
        s/\o33\[35m/<font style="color:darkorchid;">/g;
        s/\o33\[36m/<font style="color:lightseagreen;">/g;
        s/\o33\[37m/<font style="color:grey;">/g;
        s/\o33\[0m/<\/font>/g'
```

**Comment by rocka** [comment]
It does make some changes, but the appearence depends on your plasma color scheme. In my case, few colors can't be seen clearly on dark background.

Also try [ydcv-rs-git<sup>AUR</sup>](https://aur.archlinux.org/packages/ydcv-rs-git/), it provides an option to output HTML string, so you don't need to mess up with sed ;-)

Anyway, thanks for your contribution!
